### ISSUE TITLE
Unhanded error and deprecations

### ISSUE THREAD

**Issue by sixlive** [christill/generator-uniform#4]
I get this error output when I try running `yo uniform` with the example uniform.json from the README.

```
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/Users/sixlive/Desktop/test/generator-uniform/node_modules/lodash/index.js:10705:16), <anonymous>:21:55)
    at underscore (/Users/sixlive/Desktop/test/generator-uniform/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at actions.engine (/Users/sixlive/Desktop/test/generator-uniform/node_modules/yeoman-generator/lib/actions/actions.js:224:32)
    at template (/Users/sixlive/Desktop/test/generator-uniform/node_modules/yeoman-generator/lib/actions/actions.js:198:19)
    at module.exports.yeoman.generators.Base.extend.writing.javascript (/Users/sixlive/Desktop/test/generator-uniform/app/index.js:130:18)
    at /Users/sixlive/Desktop/test/generator-uniform/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by christill** [comment]
Ah ok, Let me fix that.

**Comment by christill** [comment]
Can you try now?

**Comment by sixlive** [comment]
Yeah, one sec.

**Comment by sixlive** [comment]
Still tossing the same error.

**Comment by christill** [comment]
Are you seeing this after you run yo uniform? 

![screen shot 2015-05-20 at 5 00 33 pm](https://cloud.githubusercontent.com/assets/1196417/7730423/2d411084-ff12-11e4-83e0-0688e168d318.png)

**Comment by sixlive** [comment]
This is what I get:

![screen shot 2015-05-20 at 12 27 48 pm](https://cloud.githubusercontent.com/assets/5108034/7731022/aabb94d4-feeb-11e4-9d27-b055460b2e33.png)

**Comment by christill** [comment]
hmm ok. I'll have to have a proper look. It's working fine for me.
